### ISSUE TITLE
New version!

### ISSUE THREAD

**Issue by ShaunaGordon** [xaque/aur-o3de#4]
Hey @xaque! 24.09 released a couple of days ago, and I've started getting requests to have the AUR build updated for it. 🥳

**Comment by xaque** [comment]
Thanks for the update! I am out of the country until next month and don't have an Arch machine to test on, but I've made the version bump changes in this repo, and if you are able to test that it is working, i can push it to the AUR.

If there are other changes than need to be made for this version, I am open to adding a co-maintainer on the AUR as well
